### ISSUE TITLE
Grid+MCAN using MMF

### ISSUE THREAD

**Issue by CCYChongyanChen** [facebookresearch/grid-feats-vqa#12]
Hi, I am trying to set up Grid+MCAN without using the MMF library because I would like to make it more flexible for future development: changing the dataset to the VizWiz dataset, changing GLOVE embeddings to BERT embeddings, and maybe changing the stacking strategy, etc.

Could you give me some guidance, or release the related code about setting up the grid+MCAN model reported in your paper without using MMF? Or do you think it is easier to make the changes using MMF?

Thank you!

**Comment by apsdehal** [comment]
Hi @CCYChongyanChen,

All of the things you have mentioned are already implemented in MMF and don't require any additional code. If you would like to customize it further, you can create your own fork and make changes from there on.

Let us know if you have feedback on why you think MMF isn't flexible enough or how we can make it more flexible.

**Comment by CCYChongyanChen** [comment]
> Hi @CCYChongyanChen,
> 
> All of the things you have mentioned are already implemented in MMF and don't require any additional code. If you would like to customize it further, you can create your own fork and make changes from there on.
> 
> Let us know if you have feedback on why you think MMF isn't flexible enough or how we can make it more flexible.

Hi @apsdehal ,
Thank you for your quick reply! Since MMF trains the model from end to end (start from the image), but I have extracted image grid features using this repo's code, how could I integrate the extracted grid features into the Movie+MCAN model using MMF?
Thank you!

**Comment by vedanuj** [comment]
Hi @CCYChongyanChen ,

Using features from this repo is already supported in MMF when you run Movie+MCAN model. What you will need to do is download any grid features from this repo and extract them. Then change the paths `/checkpoint/xinleic/vlfeat` in this config [file](https://github.com/facebookresearch/mmf/blob/c75f245627ccc2931b26923b7a39c39cc11b4f35/projects/movie_mcan/configs/vqa2/defaults.yaml#L14) and replace with your extracted folder.

Let us know if you face any issues. We can help.

**Comment by CCYChongyanChen** [comment]
@vedanuj  That instruction is very helpful, I appreciate it and I think now the model can find my grid features.
 
Now I am changing the dataset to vizwiz dataset by creating a mmf/projects/movie_mcan/configs/vizwiz/defaults.yaml.  When running the training code, I meet an error `-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf_cli/run.py", line 54, in distributed_main
    main(configuration, init_distributed=True, predict=predict)
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf_cli/run.py", line 40, in main
    trainer.load()
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/trainers/base_trainer.py", line 59, in load
    self.load_datasets()
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/trainers/base_trainer.py", line 83, in load_datasets
    self.dataset_loader.load_datasets()
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/common/dataset_loader.py", line 17, in load_datasets
    self.train_dataset.load(self.config)
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/datasets/multi_dataset_loader.py", line 114, in load
    self.build_datasets(config)
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/datasets/multi_dataset_loader.py", line 131, in build_datasets
    dataset_instance = build_dataset(dataset, dataset_config, self.dataset_type)
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/utils/build.py", line 106, in build_dataset
    dataset = builder_instance.load_dataset(config, dataset_type)
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/datasets/base_dataset_builder.py", line 96, in load_dataset
    dataset = self.load(config, dataset_type, *args, **kwargs)
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/datasets/mmf_dataset_builder.py", line 141, in load
    dataset = dataset_class(config, dataset_type, imdb_idx)
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/datasets/builders/vizwiz/dataset.py", line 16, in __init__
    **kwargs
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/datasets/builders/vqa2/dataset.py", line 20, in __init__
    super().__init__(name, config, dataset_type, index=imdb_file_index)
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/datasets/mmf_dataset.py", line 25, in __init__
    self.annotation_db = self._build_annotation_db()
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/datasets/mmf_dataset.py", line 39, in _build_annotation_db
    return AnnotationDatabase(self.config, annotation_path)
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/datasets/databases/annotation_database.py", line 24, in __init__
    self._load_annotation_db(path)
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/datasets/databases/annotation_database.py", line 34, in _load_annotation_db
    self._load_json(path)
  File "/home/cc67459/MMF2/lib/python3.7/site-packages/mmf/datasets/databases/annotation_database.py", line 67, in _load_json
    self.metadata = data.get("metadata", {})
AttributeError: 'list' object has no attribute 'get'
`.

I think it is because of the input format of the annotation file. I was using the annotations file directly downloaded from VizWiz website. Do I need to make an adjustment to the annotation file?
Or I shouldn't download the annotation file myself but the code will automatically download it?
 
========
Updates: The annotation file for vqa2 or VG is not downloaded automatically as the document said. I guess my question now is where can I find those annotation files, e.g.,        - vqa2/grid_features/annotations/imdb_train2014.npy, 
vizwiz/v2019/annotations/imdb_vizwiz_test.npy

Thank you!

**Comment by CCYChongyanChen** [comment]
Updates: 
The annotation file will be downloaded automatically. I found it in /.cache/torch/mmf/data/datasets/vizwiz/v2019/annoataions/imdb_vizwiz_train.npy.


Now I have a new error:

`Traceback (most recent call last):
  File "/home/cc67459/MMF2/lib/python3.7/si                                 te-packages/torch/multiprocessing/spawn.py"                                 , line 20, in _wrap
    fn(i, *args)
  File "/home/cc67459/MMF2/lib/python3.7/si                                 te-packages/mmf_cli/run.py", line 54, in di                                 stributed_main
    main(configuration, init_distributed=Tr                                 ue, predict=predict)
  File "/home/cc67459/MMF2/lib/python3.7/si                                 te-packages/mmf_cli/run.py", line 40, in ma                                 in
    trainer.load()
  File "/home/cc67459/MMF2/lib/python3.7/si                                 te-packages/mmf/trainers/base_trainer.py",                                  line 60, in load
    self.load_model_and_optimizer()
  File "/home/cc67459/MMF2/lib/python3.7/si                                 te-packages/mmf/trainers/base_trainer.py",                                  line 112, in load_model_and_optimizer
    self.model = build_model(attributes)
  File "/home/cc67459/MMF2/lib/python3.7/si                                 te-packages/mmf/utils/build.py", line 62, i                                 n build_model
    model = model_class(config)
TypeError: 'NoneType' object is not callabl                                 e`


I am at the "master" branch, should I check out to other branches? like this issue: https://github.com/facebookresearch/mmf/issues/236, Thank you.

**Comment by vedanuj** [comment]
@CCYChongyanChen Let's discuss mmf specific issues in the mmf repo. We will reply to your queries there. Thanks!

**Comment by endernewton** [comment]
Marking this as resolved
