### ISSUE TITLE
RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by vince2003** [facebookresearch/grid-feats-vqa#25]
Hello,
I get ERROR the following as;
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/media/vinh/DATA_4T/emotion_sketch/grid-feats-vqa-master/train_net.py", line 120, in main
    return trainer.train()
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 380, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/media/vinh/DATA_4T/emotion_sketch/grid-feats-vqa-master/train_net.py", line 73, in run_step
    loss_dict = self.model(data)
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 130, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 555, in forward
    losses = self._forward_box(features, proposals)
  File "/media/vinh/DATA_4T/emotion_sketch/grid-feats-vqa-master/grid_feats/roi_heads.py", line 210, in _forward_box
    box_features = self.box_pooler(features, [x.proposal_boxes for x in proposals])
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/modeling/poolers.py", line 215, in forward
    return self.level_poolers[0](x[0], pooler_fmt_boxes)
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/layers/roi_align.py", line 95, in forward
    input, rois, self.output_size, self.spatial_scale, self.sampling_ratio, self.aligned
  File "/home/vinh/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/layers/roi_align.py", line 20, in forward
    input, roi, spatial_scale, output_size[0], output_size[1], sampling_ratio, aligned
RuntimeError: Not compiled with GPU support

Can you help?

**Comment by endernewton** [comment]
Your detectron2 is not installed properly, not compiled with GPU
