### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'train_on_pred_boxes'

### ISSUE THREAD

**Issue by xiaonanQua** [facebookresearch/grid-feats-vqa#6]
Hi, thank you very much for your open source.
I found a problem while executing your code. 
I am executing, `python train_net.py --config-file configs/R-50-grid.yaml`
it exploded the following error. 
```
Traceback (most recent call last):
  File "train_net.py", line 92, in <module>
    launch(
  File "/home/team/xiaonan/xiaonan_venv/detectron2/detectron2/engine/launch.py", line 57, in launch
    main_func(*args)
  File "train_net.py", line 84, in main
    trainer = Trainer(cfg)
  File "/home/team/xiaonan/xiaonan_venv/detectron2/detectron2/engine/defaults.py", line 274, in __init__
    model = self.build_model(cfg)
  File "/home/team/xiaonan/xiaonan_venv/detectron2/detectron2/engine/defaults.py", line 419, in build_model
    model = build_model(cfg)
  File "/home/team/xiaonan/xiaonan_venv/detectron2/detectron2/modeling/meta_arch/build.py", line 21, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/team/xiaonan/xiaonan_venv/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 35, in __init__
    self.roi_heads = build_roi_heads(cfg, self.backbone.output_shape())
  File "/home/team/xiaonan/xiaonan_venv/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 43, in build_roi_heads
    return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
  File "/home/team/xiaonan/grid_vqa/grid_feats/roi_heads.py", line 179, in __init__
    super(StandardROIHeads, self).__init__(cfg, input_shape)
  File "/home/team/xiaonan/xiaonan_venv/detectron2/detectron2/config/config.py", line 152, in wrapped
    init_func(self, **explicit_args)
TypeError: __init__() got an unexpected keyword argument 'train_on_pred_boxes'
```
I don't understand whether it is an internal error in detector2 or the error in the configuration file above.

**Comment by endernewton** [comment]
Is this a fresh install of D2 on your machine?

**Comment by endernewton** [comment]
Updated the code since detectron2 changed their interface. Right now it should be find to train grid features. region features are still broken (I suspect it is also broken for C4-based models in detectron2) and can be updated later.

**Comment by apsdehal** [comment]
@endernewton It might be better to fix the commit of detectron2 on which you depend and add that directly to installation docs.

**Comment by endernewton** [comment]
Okay thanks @apsdehal, I just did that and updated the doc. @xiaonanQua please use the fixed commit mentioned in the doc.

**Comment by CCYChongyanChen** [comment]
Hi. Thank you for the code. 
I also meet the error mentioned here and then I use the fixed commit.  This error is addressed but I have another problem `"CUDA error: invalid device function".`
I guess I don't have the right CUDA and pytorch version. Could you update the "readme.md" about the right CUDA and pytorch version?
Thank you!

**Comment by endernewton** [comment]
Did you check if you can run D2 (e.g. for COCO training)? Ideally the code should work for any version that D2 supports.

**Comment by CCYChongyanChen** [comment]
I fixed "`CUDA error: invalid device function`" by setting the CUDA to 10.0 and pytorch version to 1.2. 

However now it shows "`__init__() missing 4 required positional arguments: 'code','msg','hdrs', and 'fp'"`
Do you have any idea of that? It seems unrelated to D2. Thank you.



```
Traceback (most recent call last):
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/cc67459/gridfeature/grid-feats-vqa/train_net.py", line 70, in run_step
    data = next(self._data_loader_iter)
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/detectron2/data/common.py", line 140, in __iter__
    for d in self.dataset:
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 4 required positional arguments: 'code', 'msg', 'hdrs', and 'fp'
[07/13 19:54:45 d2.engine.hooks]: Total training time: 0:00:12 (0:00:00 on hooks)
Traceback (most recent call last):
  File "train_net.py", line 133, in <module>
    args=(args,),
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/detectron2/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/home/cc67459/gridfeature/grid-feats-vqa/train_net.py", line 119, in main
    return trainer.train() #return self._last_eval_results
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 380, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/cc67459/gridfeature/grid-feats-vqa/train_net.py", line 70, in run_step
    data = next(self._data_loader_iter)
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/detectron2/data/common.py", line 140, in __iter__
    for d in self.dataset:
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/cc67459/gridfeature/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 4 required positional arguments: 'code', 'msg', 'hdrs', and 'fp'

```



Update:
I fixed it.
This error relates to the input image.
