### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by yestinl** [facebookresearch/grid-feats-vqa#7]
running command 
`python train_net.py --num-gpus 1 --config-file R-50.pth

`

Bad key "text.kerning_factor" on line 4 in
/data1/lyx/anaconda3/envs/detect-grid/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
Command Line Args: Namespace(config_file='R-50.pth', dist_url='tcp://127.0.0.1:50171', eval_only=False, machine_rank=0, num_gpus=1, num_machines=1, opts=[], resume=False)
Traceback (most recent call last):
  File "train_net.py", line 98, in <module>
    args=(args,),
  File "/data3/lyx/project/detectron2/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "train_net.py", line 72, in main
    cfg = setup(args)
  File "train_net.py", line 64, in setup
    cfg.merge_from_file(args.config_file)
  File "/data3/lyx/project/detectron2/detectron2/config/config.py", line 26, in merge_from_file
    loaded_cfg = _CfgNode.load_yaml_with_base(cfg_filename, allow_unsafe=allow_unsafe)
  File "/data1/lyx/anaconda3/envs/detect-grid/lib/python3.6/site-packages/fvcore/common/config.py", line 51, in load_yaml_with_base
    cfg = yaml.safe_load(f)
  File "/data1/lyx/anaconda3/envs/detect-grid/lib/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/data1/lyx/anaconda3/envs/detect-grid/lib/python3.6/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/data1/lyx/anaconda3/envs/detect-grid/lib/python3.6/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/data1/lyx/anaconda3/envs/detect-grid/lib/python3.6/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/data1/lyx/anaconda3/envs/detect-grid/lib/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/data1/lyx/anaconda3/envs/detect-grid/lib/python3.6/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/data1/lyx/anaconda3/envs/detect-grid/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by endernewton** [comment]
Note that please use a *..yaml* file as a config, NOT the ".pth" file.
